// Generated by SeasonalPerks/tools/sync_ui_preview.py. Edit the UI project source.
#nullable enable
namespace SeasonalPerks.UI
{

public enum InterfaceSound
{
    None,
    ButtonHover,
    ButtonClick,
    Back,
    PerkOn,
    PerkOff,
    PerkReset,
}

}
